global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#devops'